### ISSUE TITLE
Server Side Documentation

### ISSUE THREAD

**Issue by hasdf** [andyvalerio/photoprism-geolocation#1]
Hi,

thanks for your plugin. Do you mind documenting how to implement it? As far as I can see, installing only the chrome extension is not enough.

Thank You

**Comment by andyvalerio** [comment]
Hi! You don't actually need to implement anything, it is enough to install the chrome extension. 
You might need to refresh the PhotoPrism web page once (or twice!) after you install the extension though. 

If that still doesn't do the trick for you, could you send me the extension logs? Perhaps there will be something useful there that tells me why it fails in your case. Alternatively, just contact me in private and we can have a quick call so you can show me how it looks for you.

**Comment by hasdf** [comment]
Thank you for your help! Works fine now

I don't know what went wrong. just used the code in the repository to install the extension. 

Didn't work with https://chrome.google.com/webstore/detail/geolocation-plugin-for-ph/oggmpodnbdcmfiognbkkeffacpeaifch?hl=en
