### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by apsmith12** [andyvalerio/photoprism-geolocation#11]
When trying to save an item using the icon on the bottom right, the following error is thrown when trying to save.
![image](https://github.com/user-attachments/assets/c88d1944-0aa3-482d-a765-faff24f83c1f)

**Comment by andyvalerio** [comment]
Hi @apsmith12, 
what do you mean by "trying to save an item"? Are you editing a single image or using the bulk edit? 
Can you describe the scenario a bit more in detail so we can try to reproduce it? 

Thanks
Andy

**Comment by keif888** [comment]
Hi Andy,
This is happening in the bulk change save code.
For some reason the photo_clipboard local storage variable, which is maintained by PhotoPrism was null when apsmith12 clicked on the save button.
See the null contentScriot,js:189 line in the log above which logs that out.  It should have contained at least ["photouid"] where the photouid corresponds to a photo unique identifier from PhotoPrism.  eg. ["psmljme7onzvo1bd","psmljmdzsor6v5so"]

I haven't been able to replicate this issue against https://demo.photoprism.app/.
As soon as the last selected photo is deselected (which nulls photo_clipboard) the save button disappears.  Even if I have the map up to select the coordinates.

@apsmith12 can you please let us know what version of PhotoPrism you are using, and what actions you took before clicking on Save?

**Comment by apsmith12** [comment]
PhotoPrism® CE
Build 240915-e1280b2fb

**Comment by andyvalerio** [comment]
Hi @apsmith12, 
we haven't been able to replicate this behavior so far. Could you let us know precisely the steps you execute? 

Even better if you try to execute it against https://demo.photoprism.app/ so that we know it has nothing to do with your local setup. 
That would be really helpful. 

Thanks!
Andy

**Comment by apsmith12** [comment]
So, I went to the demo site, it worked fine.  I returned to my instance and it seemed to work.  No idea what changed, but I can close this until something happens again.
