### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by xplosionmind** [andyvalerio/photoprism-geolocation#2]
It would be awesome and lovely if a Firefox extension could be created, too!

**Comment by andyvalerio** [comment]
Hi Tommi, 
yes, it would be. Do you know anyone with the right skillset to make it happen? I won't be able to focus on this and do it myself for at least a few months from now.
Thanks, 
Andy

**Comment by xplosionmind** [comment]
Unfortunately, I do not 😢

**Comment by andyvalerio** [comment]
Alright, I'll set a reminder for myself to implement it when I have a bit more free time.

**Comment by FranGarc** [comment]
Hi! Is there any chances we get to see the Firefox version?

**Comment by andyvalerio** [comment]
Hi @FranGarc, 
I don't have time to prioritize that work at the moment, unfortunately. I have a reminder about this every few months, but there is always something more important to do. 😮‍💨

**Comment by keif888** [comment]
@andyvalerio I am working on this here [BrowserIndependant](https://github.com/keif888/photoprism-geolocation/tree/BrowserIndependant), but it's not ready yet.
