### ISSUE TITLE
Extension appears not to work in Chrome 103.x on macOS

### ISSUE THREAD

**Issue by dinoschachten** [andyvalerio/photoprism-geolocation#3]
Hi,

I hope me opening an issue out of the blue is appropriate - if not, feel free to delete ;)

Problem:
It seems like the extension does not do anything in Chrome 103.0.5060.134

Steps to reproduce:
- I've tried both cloning from Github (following the steps described on this page) and installation from the Chrome Store on different Macs.
- Checking the details view from various pages in Photoprism, I didn't see any map or any difference at all in the detail view for photos or videos
- Environment: macOS 10.13, macOS 10.15, Chrome 103 (103.0.5060.134)

Minor sidenote: On this Github page there appears to be no description of how the extension should work after installation.

**Comment by andyvalerio** [comment]
Hi Dino, 
thanks for reporting that, it's always useful to receive feedback. 

The extension wasn't tested on macOS but I think it should work anyway. I don't have a Mac (I'm getting one in August actually, so I'll be able to test this case) and more importantly I don't have a lot of bandwidth right now to work on this 😣. 

I suggest that you try the following two things, if possible, as they seem to solve most of the issues. 
- refresh the page (or even better restart Chrome) after installing the extension, I received some reports that it doesn't "bite" at the first attempt 
- if that doesn't work, make sure that you're opening and editing the image from the "Search" menu item, in some cases the map doesn't open when you edit images from other sub-menus
![image](https://user-images.githubusercontent.com/11454941/180437700-65657f8b-631f-4571-9b4f-b87c91931015.png)

**Comment by dinoschachten** [comment]
Hi Andy,

thanks so much for the quick response! I had restarted Chrome after the installation without success, however after force-reloading the page just now it does work - thanks for the tip!
